### PR TITLE
Now codepage still has initial value after calling getInstallations() method (closes #58)

### LINKED ISSUE #58: The 'write EIO' error appeared when console trying to write unicode symbols after getInstallations() method call.
At this moment API method getInstallations() changes codepage during his execution.
[findWindowsBrowsers() method](https://github.com/DevExpress/testcafe-browser-natives/blob/master/src/api/get-installations.js#L44)
[detectMicrosoftEdge() method](https://github.com/DevExpress/testcafe-browser-natives/blob/master/src/api/get-installations.js#L32)
If terminal's default codepage is different from 65001 (437 in our case), it's going to crash TestCafe when trying to display unicode symbols after this change.
To check default codepage run in command line:
``` cmd
chcp
```

### PR DESCRIPTION
**Pull request by georgiy-abbasov**
\cc @inikulin, @AlexanderMoskovkin, @VasilyStrelyaev
PR

### CODE REVIEW

File: src/api/get-installations.js [hunk 1]
```diff
@@ -59,6 +64,8 @@ async function findWindowsBrowsers () {
     if (edgeAlias)
         installations['edge'] = edgeAlias;
 
+    await exec(`chcp ${origCodePage}`);
```
Comment (inikulin) [inline src/api/get-installations.js]: Let's do it immediately after obtaining stdout

**Comment by inikulin** [comment]
\r-

File: src/api/get-installations.js (hunk 1 above)
Comment (georgiy-abbasov) [inline src/api/get-installations.js]: In that case we should write same code after this line too. It's ok ?
[async function detectMicrosoftEdge () ](https://github.com/DevExpress/testcafe-browser-natives/blob/master/src/api/get-installations.js#L32)

Comment (inikulin) [inline src/api/get-installations.js]: Well, I see now. We have an incosistency here, I can break things by calling `detectMicrosoftEdge` directly. What we need to do here: create `setCmdCodePage()` and `restoreCmdCodePage` methods and call them from `getWindowsBrowser` to make things more  explicit.

**Comment by georgiy-abbasov** [comment]
FRP

File: src/api/get-installations.js [hunk 2]
```diff
@@ -59,6 +86,7 @@ async function findWindowsBrowsers () {
     if (edgeAlias)
         installations['edge'] = edgeAlias;
 
+
```
Comment (AlexanderMoskovkin) [inline src/api/get-installations.js]: Now you change the code page 5 times instead of 2:
[one](https://github.com/DevExpress/testcafe-browser-natives/pull/59/files#diff-d30903c8763835cd105158ddd2fcb731R67), [two](https://github.com/DevExpress/testcafe-browser-natives/pull/59/files#diff-d30903c8763835cd105158ddd2fcb731R71), [three](https://github.com/DevExpress/testcafe-browser-natives/pull/59/files#diff-d30903c8763835cd105158ddd2fcb731R51), [four](https://github.com/DevExpress/testcafe-browser-natives/pull/59/files#diff-d30903c8763835cd105158ddd2fcb731R53), [five](https://github.com/DevExpress/testcafe-browser-natives/pull/59/files#diff-d30903c8763835cd105158ddd2fcb731R55)

But we should have just the following:
```js
findWindowsBrowsers () {
    setCodePage(65001);
    
    //do smthg
    detectMicrosoftEdge();
    //do smthg

    restoreCodePage();
    return ...;
}
```

Comment (georgiy-abbasov) [inline src/api/get-installations.js]: four - is my mistake, forgot to fix argument.
About other cases: i thought, it's more safe, because at moment '//do smthg'  there can be any other call to process.stdout.write()

Comment (AlexanderMoskovkin) [inline src/api/get-installations.js]: > any other call to process.stdout.write()

Where?
```js
var installations = {};
    var regKey        = 'HKEY_LOCAL_MACHINE\\SOFTWARE\\Clients\\StartMenuInternet\\';
    var regKeyEsc     = regKey.replace(/\\/g, '\\\\');
    var browserRe     = new RegExp(regKeyEsc + '([^\\\\]+)\\\\shell\\\\open\\\\command' +
                                   '\\s+\\([^)]+\\)\\s+reg_sz\\s+([^\n]+)\n', 'gi');

    setCodePage(65001);

    var stdout = await exec(`reg query ${regKey} /s`);

    restoreCodePage();

    for (var match = browserRe.exec(stdout); match; match = browserRe.exec(stdout)) {
        var name = match[1].replace(/\.exe$/gi, '');

        var path = match[2]
            .replace(/"/g, '')
            .replace(/\\$/, '')
            .replace(/\s*$/, '');

        await addInstallation(installations, name, path);
    }

    var edgeAlias = await detectMicrosoftEdge();

    if (edgeAlias)
        installations['edge'] = edgeAlias;


    return installations;
```

Comment (georgiy-abbasov) [inline src/api/get-installations.js]: Not here, i mean any application callback at background, which can be during addInstallation() execution.

Comment (AlexanderMoskovkin) [inline src/api/get-installations.js]: There is no such thing

**Comment by georgiy-abbasov** [comment]
FPR

File: src/api/get-installations.js [hunk 3]
```diff
@@ -41,7 +60,11 @@ async function findWindowsBrowsers () {
     var browserRe     = new RegExp(regKeyEsc + '([^\\\\]+)\\\\shell\\\\open\\\\command' +
                                    '\\s+\\([^)]+\\)\\s+reg_sz\\s+([^\n]+)\n', 'gi');
 
-    var stdout = await exec(`chcp 65001 | reg query ${regKey} /s`);
+    // NOTE: we should change code page to get correct result regardless the WIndows localization.
```
Comment (AlexanderMoskovkin) [inline src/api/get-installations.js]: @MargaritaLoseva Please, check the comment

File: src/api/get-installations.js [hunk 4]
```diff
@@ -41,7 +60,11 @@ async function findWindowsBrowsers () {
...
+    // Then we should restore it to avoid the terminal errors.
```
Comment (AlexanderMoskovkin) [inline src/api/get-installations.js]: @MargaritaLoseva Please, check the comment

File: src/api/get-installations.js [hunk 5]
```diff
@@ -29,7 +47,8 @@ async function addInstallation (installations, name, instPath) {
 
 async function detectMicrosoftEdge () {
     var regKey = 'HKCU\\Software\\Classes\\ActivatableClasses';
-    var stdout = await exec(`chcp 65001 | reg query ${regKey} /s /f MicrosoftEdge /k && echo SUCCESS || echo FAIL`);
+
```
Comment (AlexanderMoskovkin) [inline src/api/get-installations.js]: No need for this odd line break

File: src/api/get-installations.js (hunk 3 above)
Comment (MargaritaLoseva) [inline src/api/get-installations.js]: Changed comment:

// NOTE: we need to change the code page to get the correct result regardless of the Windows localization.
// Then we need to restore it to avoid terminal errors.

Comment (georgiy-abbasov) [inline src/api/get-installations.js]: Thanks

Comment (AlexanderMoskovkin) [inline src/api/get-installations.js]: @georgiy-abbasov Correct formatting a little:
```js
// NOTE: we need to change the code page to get the correct result regardless of
// the Windows localization. Then we need to restore it to avoid terminal errors.
```

**Comment by georgiy-abbasov** [comment]
FPR

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
\cc @AndreyBelym

File: src/api/get-installations.js [hunk 6]
```diff
@@ -8,6 +8,24 @@ import ALIASES from '../aliases';
 // Installation info cache
 var installationsCache = null;
 
+// Original code page value
+var origCodePage = null;
```
Comment (inikulin) [inline src/api/get-installations.js]: Never use global vars in async envirionment. Imagine the following scenario:
there are two `getInstallations` running at the same time, the first one sets `origCodePage` to the initial. Then second one tries to save original code page, but it's already modified by the first one. Think how we can avoid this.

**Comment by inikulin** [comment]
\r-

File: src/api/get-installations.js (hunk 6 above)
Comment (georgiy-abbasov) [inline src/api/get-installations.js]: Can we do by that way ?
[simplified scheme](https://gist.github.com/georgiy-abbasov/98db1990a7e6ea48bd6d)

**Comment by georgiy-abbasov** [comment]
FPR

**Comment by VasilyStrelyaev** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
lgtm

File: src/api/get-installations.js (hunk 6 above)
Comment (inikulin) [inline src/api/get-installations.js]: Too complicated. It can be done in much simpler manner. Here is a tip: if we can set desired code page and obtain results in single `cmd` execution maybe we can restore original code page there as well?

**Comment by georgiy-abbasov** [comment]
@inikulin, @AlexanderMoskovkin
fpr

File: src/api/get-installations.js [hunk 7]
```diff
@@ -9,6 +9,13 @@ import ALIASES from '../aliases';
 var installationsCache = null;
 
 
+async function execWithCodePage (command, codePage) {
```
Comment (inikulin) [inline src/api/get-installations.js]: We can move it to `src/utils/exec`. Also, I don't think we need to pass `codePage` around. `65001` is UTF8 codepage (see: https://msdn.microsoft.com/ru-ru/library/windows/desktop/dd317756(v=vs.85).aspx). We can name function `execWinShellUtf8` or smthg like that. \cc @VasilyStrelyaev

**Comment by inikulin** [comment]
\r-

File: src/api/get-installations.js (hunk 7 above)
Comment (VasilyStrelyaev) [inline src/api/get-installations.js]: ok

**Comment by georgiy-abbasov** [comment]
fpr

File: src/api/get-installations.js [hunk 8]
```diff
@@ -41,7 +41,8 @@ async function findWindowsBrowsers () {
     var browserRe     = new RegExp(regKeyEsc + '([^\\\\]+)\\\\shell\\\\open\\\\command' +
                                    '\\s+\\([^)]+\\)\\s+reg_sz\\s+([^\n]+)\n', 'gi');
 
-    var stdout = await exec(`chcp 65001 | reg query ${regKey} /s`);
+    // NOTE: We need to get the correct result regardless of the Windows localization.
```
Comment (VasilyStrelyaev) [inline src/api/get-installations.js]: Cap!

File: src/utils/exec.js [hunk 9]
```diff
@@ -23,3 +23,12 @@ export async function execFile (filePath, args) {
 export async function exec (command) {
     return await execPromise(command);
 }
+
+export async function execWinShellUtf8 (command) {
+    var setCodePageCmd     = `FOR /F  "tokens=2 delims=:" %i in ('chcp') do (chcp 65001`;
+
+    // NOTE: To avoid terminal errors, we need to restore original code page after command is executed.
```
Comment (VasilyStrelyaev) [inline src/utils/exec.js]: Please use the exact text I give you:
image
```
To avoid terminal errors, we need to restore the original code page after the command is executed.
```

File: src/api/get-installations.js [hunk 10]
```diff
@@ -65,14 +66,14 @@ async function findWindowsBrowsers () {
 async function findMacBrowsers () {
     var installations = {};
 
-    //NOTE: replace space symbol with the code, because grep splits strings by space.
+    // NOTE: replace space symbol with the code, because grep splits strings by space.
```
Comment (VasilyStrelyaev) [inline src/api/get-installations.js]:
```
    // NOTE: replace the space symbol with code, because grep splits strings by space.
```

File: src/api/get-installations.js (hunk 8 above)
Comment (VasilyStrelyaev) [inline src/api/get-installations.js]: Did you want to say smth like:
```
    // NOTE: To get the correct result regardless of the Windows localization, we need to switch the codepage to UTF-8.
```

**Comment by georgiy-abbasov** [comment]
fpr

File: src/utils/exec.js [hunk 11]
```diff
@@ -23,3 +23,12 @@ export async function execFile (filePath, args) {
 export async function exec (command) {
     return await execPromise(command);
 }
+
+export async function execWinShellUtf8 (command) {
+    var setCodePageCmd     = `FOR /F  "tokens=2 delims=:" %i in ('chcp') do (chcp 65001`;
+
+    // NOTE: To avoid terminal errors, we need to restore the original code page after the command is executed.
```
Comment (inikulin) [inline src/utils/exec.js]: Style nit: better place this comment above `return` statement

**Comment by inikulin** [comment]
Overall looks good, just a little style nit

**Comment by georgiy-abbasov** [comment]
@inikulin, comment moved so please review once again.
@AlexanderMoskovkin and @VasilyStrelyaev, it's ok overall ?

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by inikulin** [comment]
lgtm

**Comment by VasilyStrelyaev** [comment]
lgtm

**Comment by inikulin** [comment]
We need to release new version with this fix and update testcafe deps

**Comment by AlexanderMoskovkin** [comment]
I'll do this.

This is a minor version update (to 0.10.3). `testcafe` has `"testcafe-browser-natives": "^0.10.0"` in the dependencies. Do we need update testcafe deps nevertheless?

**Comment by inikulin** [comment]
@AlexanderMoskovkin nope
